blueprint:
  name: "IKEA BILRESA Dual Button"
  description: "Control lights with the IKEA BILRESA dual button. Supports single press, double press, and long press for each button. Long press enables smooth dimming."
  domain: automation
  input:
    # Button entities
    button_1_entity:
      name: "Button 1 Entity"
      description: "The event entity for button 1 (typically the top/left button)"
      selector:
        entity:
          domain: event

    button_2_entity:
      name: "Button 2 Entity"
      description: "The event entity for button 2 (typically the bottom/right button)"
      selector:
        entity:
          domain: event

    # Target light
    target_light:
      name: "Target Light"
      description: "The light to control"
      selector:
        entity:
          domain: light

    # Button 1 actions
    button_1_single_action:
      name: "Button 1: Single Press Action"
      description: "What happens when button 1 is pressed once"
      default: "turn_on"
      selector:
        select:
          options:
            - label: "Turn On"
              value: "turn_on"
            - label: "Turn Off"
              value: "turn_off"
            - label: "Toggle"
              value: "toggle"
            - label: "Full Brightness (100%)"
              value: "full_brightness"
            - label: "Custom Brightness"
              value: "custom_brightness"

    button_1_single_brightness:
      name: "Button 1: Single Press Brightness"
      description: "Brightness level for 'Custom Brightness' action (percentage)"
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    button_1_double_action:
      name: "Button 1: Double Press Action"
      description: "What happens when button 1 is pressed twice"
      default: "full_brightness"
      selector:
        select:
          options:
            - label: "Turn On"
              value: "turn_on"
            - label: "Turn Off"
              value: "turn_off"
            - label: "Toggle"
              value: "toggle"
            - label: "Full Brightness (100%)"
              value: "full_brightness"
            - label: "Custom Brightness"
              value: "custom_brightness"
            - label: "Warm Light (2700K)"
              value: "warm_light"
            - label: "Cool Light (5000K)"
              value: "cool_light"

    button_1_double_brightness:
      name: "Button 1: Double Press Brightness"
      description: "Brightness level for 'Custom Brightness' action (percentage)"
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # Button 2 actions
    button_2_single_action:
      name: "Button 2: Single Press Action"
      description: "What happens when button 2 is pressed once"
      default: "turn_off"
      selector:
        select:
          options:
            - label: "Turn On"
              value: "turn_on"
            - label: "Turn Off"
              value: "turn_off"
            - label: "Toggle"
              value: "toggle"
            - label: "Dim Light (10%)"
              value: "dim_light"
            - label: "Custom Brightness"
              value: "custom_brightness"

    button_2_single_brightness:
      name: "Button 2: Single Press Brightness"
      description: "Brightness level for 'Custom Brightness' action (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    button_2_double_action:
      name: "Button 2: Double Press Action"
      description: "What happens when button 2 is pressed twice"
      default: "dim_light"
      selector:
        select:
          options:
            - label: "Turn On"
              value: "turn_on"
            - label: "Turn Off"
              value: "turn_off"
            - label: "Toggle"
              value: "toggle"
            - label: "Dim Light (10%)"
              value: "dim_light"
            - label: "Custom Brightness"
              value: "custom_brightness"
            - label: "Warm Light (2700K)"
              value: "warm_light"
            - label: "Cool Light (5000K)"
              value: "cool_light"

    button_2_double_brightness:
      name: "Button 2: Double Press Brightness"
      description: "Brightness level for 'Custom Brightness' action (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    # Long press dimming settings
    long_press_action:
      name: "Long Press Behavior"
      description: "What happens during long press"
      default: "dim"
      selector:
        select:
          options:
            - label: "Button 1 increases, Button 2 decreases brightness"
              value: "dim"
            - label: "Disabled"
              value: "disabled"

    dimming_step:
      name: "Dimming Step"
      description: "How much to change brightness per step during long press (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 25
          unit_of_measurement: "%"

    dimming_speed:
      name: "Dimming Speed"
      description: "Delay between dimming steps (milliseconds). Lower = faster dimming."
      default: 200
      selector:
        number:
          min: 50
          max: 500
          unit_of_measurement: "ms"

    min_brightness:
      name: "Minimum Brightness"
      description: "Minimum brightness during dimming (prevents turning off)"
      default: 5
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    max_brightness:
      name: "Maximum Brightness"
      description: "Maximum brightness during dimming"
      default: 100
      selector:
        number:
          min: 50
          max: 100
          unit_of_measurement: "%"

    transition_time:
      name: "Transition Time"
      description: "How long light takes to transition (seconds)"
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "s"

trigger:
  # Button 1 triggers
  - platform: state
    entity_id: !input button_1_entity
    id: button_1
  # Button 2 triggers
  - platform: state
    entity_id: !input button_2_entity
    id: button_2

action:
  - variables:
      target: !input target_light
      event_type: "{{ trigger.to_state.attributes.event_type }}"
      # Button 1 settings
      b1_single_action: !input button_1_single_action
      b1_single_brightness: !input button_1_single_brightness
      b1_double_action: !input button_1_double_action
      b1_double_brightness: !input button_1_double_brightness
      # Button 2 settings
      b2_single_action: !input button_2_single_action
      b2_single_brightness: !input button_2_single_brightness
      b2_double_action: !input button_2_double_action
      b2_double_brightness: !input button_2_double_brightness
      # Dimming settings
      long_press_enabled: !input long_press_action
      dim_step: !input dimming_step
      dim_speed: !input dimming_speed
      brightness_min: !input min_brightness
      brightness_max: !input max_brightness
      transition: !input transition_time

  - choose:
      # ==================== BUTTON 1 ====================

      # Button 1: Single press
      - conditions:
          - condition: trigger
            id: button_1
          - condition: template
            value_template: "{{ event_type == 'multi_press_1' }}"
        sequence:
          - choose:
              - conditions: "{{ b1_single_action == 'turn_on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b1_single_action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b1_single_action == 'toggle' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ target }}"
              - conditions: "{{ b1_single_action == 'full_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: 100
              - conditions: "{{ b1_single_action == 'custom_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: "{{ b1_single_brightness }}"

      # Button 1: Double press
      - conditions:
          - condition: trigger
            id: button_1
          - condition: template
            value_template: "{{ event_type == 'multi_press_2' }}"
        sequence:
          - choose:
              - conditions: "{{ b1_double_action == 'turn_on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b1_double_action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b1_double_action == 'toggle' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ target }}"
              - conditions: "{{ b1_double_action == 'full_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: 100
              - conditions: "{{ b1_double_action == 'custom_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: "{{ b1_double_brightness }}"
              - conditions: "{{ b1_double_action == 'warm_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      color_temp_kelvin: 2700
              - conditions: "{{ b1_double_action == 'cool_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      color_temp_kelvin: 5000

      # Button 1: Long press (increase brightness)
      - conditions:
          - condition: trigger
            id: button_1
          - condition: template
            value_template: "{{ event_type == 'long_press' and long_press_enabled == 'dim' }}"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input button_1_entity
                  attribute: event_type
                  state: "long_press"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ target }}"
                  data:
                    transition: "{{ transition }}"
                    brightness_pct: >-
                      {% set current = state_attr(target, 'brightness') %}
                      {% if current is none %}
                        {% set current_pct = 50 %}
                      {% else %}
                        {% set current_pct = (current / 255 * 100) | round(0) %}
                      {% endif %}
                      {{ [[current_pct + dim_step, brightness_min] | max, brightness_max] | min }}
                - delay:
                    milliseconds: "{{ dim_speed }}"

      # ==================== BUTTON 2 ====================

      # Button 2: Single press
      - conditions:
          - condition: trigger
            id: button_2
          - condition: template
            value_template: "{{ event_type == 'multi_press_1' }}"
        sequence:
          - choose:
              - conditions: "{{ b2_single_action == 'turn_on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b2_single_action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b2_single_action == 'toggle' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ target }}"
              - conditions: "{{ b2_single_action == 'dim_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: 10
              - conditions: "{{ b2_single_action == 'custom_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: "{{ b2_single_brightness }}"

      # Button 2: Double press
      - conditions:
          - condition: trigger
            id: button_2
          - condition: template
            value_template: "{{ event_type == 'multi_press_2' }}"
        sequence:
          - choose:
              - conditions: "{{ b2_double_action == 'turn_on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b2_double_action == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
              - conditions: "{{ b2_double_action == 'toggle' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ target }}"
              - conditions: "{{ b2_double_action == 'dim_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: 10
              - conditions: "{{ b2_double_action == 'custom_brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      brightness_pct: "{{ b2_double_brightness }}"
              - conditions: "{{ b2_double_action == 'warm_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      color_temp_kelvin: 2700
              - conditions: "{{ b2_double_action == 'cool_light' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      transition: "{{ transition }}"
                      color_temp_kelvin: 5000

      # Button 2: Long press (decrease brightness)
      - conditions:
          - condition: trigger
            id: button_2
          - condition: template
            value_template: "{{ event_type == 'long_press' and long_press_enabled == 'dim' }}"
        sequence:
          - repeat:
              while:
                - condition: state
                  entity_id: !input button_2_entity
                  attribute: event_type
                  state: "long_press"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ target }}"
                  data:
                    transition: "{{ transition }}"
                    brightness_pct: >-
                      {% set current = state_attr(target, 'brightness') %}
                      {% if current is none %}
                        {% set current_pct = 50 %}
                      {% else %}
                        {% set current_pct = (current / 255 * 100) | round(0) %}
                      {% endif %}
                      {{ [[current_pct - dim_step, brightness_min] | max, brightness_max] | min }}
                - delay:
                    milliseconds: "{{ dim_speed }}"

mode: restart
max_exceeded: silent
