blueprint:
  name: "IKEA Bilresa Scroll Wheel – Simple Brightness Control"
  description: "Control a light's brightness using the IKEA Bilresa scroll wheel. Scroll to adjust brightness, press to toggle on/off."
  domain: automation

  input:
    scroll_right_entity:
      name: "Scroll Right Entity"
      description: "The event entity for scroll right actions"
      selector:
        entity:
          domain: event

    scroll_left_entity:
      name: "Scroll Left Entity"
      description: "The event entity for scroll left actions"
      selector:
        entity:
          domain: event

    button_press_entity:
      name: "Button Press Entity"
      description: "The event entity for button press actions"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "The light to control"
      selector:
        entity:
          domain: light

    increase_brightness_step:
      name: "Brightness Increase Step"
      description: "How much to increase brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    decrease_brightness_step:
      name: "Brightness Decrease Step"
      description: "How much to decrease brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    scroll_right_action:
      name: "Scroll Right Action"
      description: "What happens when scrolling right"
      default: "increase"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "increase"
            - label: "Decrease Brightness"
              value: "decrease"

trigger:
  - platform: state
    entity_id: !input scroll_right_entity
    id: scroll_right
  - platform: state
    entity_id: !input scroll_left_entity
    id: scroll_left
  - platform: state
    entity_id: !input button_press_entity
    id: button_press

action:
  - variables:
      target: !input target_light
      increase_step: !input increase_brightness_step
      decrease_step: !input decrease_brightness_step
      scroll_right_direction: !input scroll_right_action

  - choose:
      # Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: button_press
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ target }}"

      # Scroll right
      - conditions:
          - condition: trigger
            id: scroll_right
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target }}"
            data:
              brightness_step_pct: >-
                {% if scroll_right_direction == 'increase' %}
                  {{ increase_step }}
                {% else %}
                  {{ -decrease_step }}
                {% endif %}

      # Scroll left
      - conditions:
          - condition: trigger
            id: scroll_left
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target }}"
            data:
              brightness_step_pct: >-
                {% if scroll_right_direction == 'increase' %}
                  {{ -decrease_step }}
                {% else %}
                  {{ increase_step }}
                {% endif %}

mode: queued
max: 20