blueprint:
  name: "IKEA Bilresa Scroll Wheel – Dual Mode Control"
  description: "Control a light using the IKEA Bilresa scroll wheel. Configure both brightness and color temperature modes independently."
  domain: automation
  input:
    control_mode:
      name: "Control Mode"
      description: "Choose whether to control brightness or color temperature"
      default: "brightness"
      selector:
        select:
          options:
            - label: "Brightness Control"
              value: "brightness"
            - label: "Color Temperature Control"
              value: "temperature"

    # Mode 1: Brightness Control
    mode_1_scroll_right_entity:
      name: "Mode 1: Scroll Right Entity"
      description: "The event entity for scroll right actions (Brightness mode)"
      selector:
        entity:
          domain: event

    mode_1_scroll_left_entity:
      name: "Mode 1: Scroll Left Entity"
      description: "The event entity for scroll left actions (Brightness mode)"
      selector:
        entity:
          domain: event

    mode_1_button_press_entity:
      name: "Mode 1: Button Press Entity"
      description: "The event entity for button press actions (Brightness mode)"
      selector:
        entity:
          domain: event

    mode_1_target_light:
      name: "Mode 1: Target Light"
      description: "The light to control (Brightness mode)"
      selector:
        entity:
          domain: light

    mode_1_increase_brightness_step:
      name: "Mode 1: Brightness Increase Step"
      description: "How much to increase brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    mode_1_decrease_brightness_step:
      name: "Mode 1: Brightness Decrease Step"
      description: "How much to decrease brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    mode_1_scroll_right_action:
      name: "Mode 1: Scroll Right Action"
      description: "What happens when scrolling right in Brightness mode"
      default: "increase"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "increase"
            - label: "Decrease Brightness"
              value: "decrease"

    # Mode 2: Temperature Control
    mode_2_scroll_right_entity:
      name: "Mode 2: Scroll Right Entity"
      description: "The event entity for scroll right actions (Temperature mode)"
      selector:
        entity:
          domain: event

    mode_2_scroll_left_entity:
      name: "Mode 2: Scroll Left Entity"
      description: "The event entity for scroll left actions (Temperature mode)"
      selector:
        entity:
          domain: event

    mode_2_button_press_entity:
      name: "Mode 2: Button Press Entity"
      description: "The event entity for button press actions (Temperature mode)"
      selector:
        entity:
          domain: event

    mode_2_target_light:
      name: "Mode 2: Target Light"
      description: "The light to control (Temperature mode - must support color temperature)"
      selector:
        entity:
          domain: light

    mode_2_increase_temperature_step:
      name: "Mode 2: Temperature Increase Step"
      description: "How much to increase color temperature per scroll (mireds)"
      default: 30
      selector:
        number:
          min: 5
          max: 100
          unit_of_measurement: "mireds"

    mode_2_decrease_temperature_step:
      name: "Mode 2: Temperature Decrease Step"
      description: "How much to decrease color temperature per scroll (mireds)"
      default: 30
      selector:
        number:
          min: 5
          max: 100
          unit_of_measurement: "mireds"

    mode_2_scroll_right_action:
      name: "Mode 2: Scroll Right Action"
      description: "What happens when scrolling right in Temperature mode"
      default: "warmer"
      selector:
        select:
          options:
            - label: "Warmer (increase mireds)"
              value: "warmer"
            - label: "Cooler (decrease mireds)"
              value: "cooler"

    # Common settings
    automation_mode:
      name: "Automation Mode"
      description: "How to handle multiple triggers"
      default: "queued"
      selector:
        select:
          options:
            - label: "Queued (recommended for smooth scrolling)"
              value: "queued"
            - label: "Single (ignore new triggers while running)"
              value: "single"
            - label: "Restart (restart on new trigger)"
              value: "restart"
            - label: "Parallel (run multiple instances)"
              value: "parallel"

    max_queue:
      name: "Maximum Queue Size"
      description: "Maximum number of queued scroll actions (only applies in queued mode)"
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "actions"

trigger:
  # Mode 1 triggers
  - platform: state
    entity_id: !input mode_1_scroll_right_entity
    id: mode_1_scroll_right
  - platform: state
    entity_id: !input mode_1_scroll_left_entity
    id: mode_1_scroll_left
  - platform: state
    entity_id: !input mode_1_button_press_entity
    id: mode_1_button_press
  # Mode 2 triggers
  - platform: state
    entity_id: !input mode_2_scroll_right_entity
    id: mode_2_scroll_right
  - platform: state
    entity_id: !input mode_2_scroll_left_entity
    id: mode_2_scroll_left
  - platform: state
    entity_id: !input mode_2_button_press_entity
    id: mode_2_button_press

action:
  - variables:
      mode: !input control_mode
      # Mode 1 variables
      mode_1_target: !input mode_1_target_light
      mode_1_brightness_increase_step: !input mode_1_increase_brightness_step
      mode_1_brightness_decrease_step: !input mode_1_decrease_brightness_step
      mode_1_brightness_scroll_direction: !input mode_1_scroll_right_action
      # Mode 2 variables
      mode_2_target: !input mode_2_target_light
      mode_2_temp_increase_step: !input mode_2_increase_temperature_step
      mode_2_temp_decrease_step: !input mode_2_decrease_temperature_step
      mode_2_temp_scroll_direction: !input mode_2_scroll_right_action

  - choose:
      # Mode 1: Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: mode_1_button_press
          - condition: template
            value_template: "{{ mode == 'brightness' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ mode_1_target }}"

      # Mode 1: Scroll right
      - conditions:
          - condition: trigger
            id: mode_1_scroll_right
          - condition: template
            value_template: "{{ mode == 'brightness' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ mode_1_target }}"
            data:
              brightness_step_pct: >-
                {% if mode_1_brightness_scroll_direction == 'increase' %}
                  {{ mode_1_brightness_increase_step }}
                {% else %}
                  {{ -mode_1_brightness_decrease_step }}
                {% endif %}

      # Mode 1: Scroll left
      - conditions:
          - condition: trigger
            id: mode_1_scroll_left
          - condition: template
            value_template: "{{ mode == 'brightness' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ mode_1_target }}"
            data:
              brightness_step_pct: >-
                {% if mode_1_brightness_scroll_direction == 'increase' %}
                  {{ -mode_1_brightness_decrease_step }}
                {% else %}
                  {{ mode_1_brightness_increase_step }}
                {% endif %}

      # Mode 2: Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: mode_2_button_press
          - condition: template
            value_template: "{{ mode == 'temperature' }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ mode_2_target }}"

      # Mode 2: Scroll right
      - conditions:
          - condition: trigger
            id: mode_2_scroll_right
          - condition: template
            value_template: "{{ mode == 'temperature' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ mode_2_target }}"
            data:
              color_temp: >-
                {% set current = state_attr(mode_2_target, 'color_temp') | int %}
                {% if mode_2_temp_scroll_direction == 'warmer' %}
                  {{ current + mode_2_temp_increase_step }}
                {% else %}
                  {{ current - mode_2_temp_decrease_step }}
                {% endif %}

      # Mode 2: Scroll left
      - conditions:
          - condition: trigger
            id: mode_2_scroll_left
          - condition: template
            value_template: "{{ mode == 'temperature' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ mode_2_target }}"
            data:
              color_temp: >-
                {% set current = state_attr(mode_2_target, 'color_temp') | int %}
                {% if mode_2_temp_scroll_direction == 'warmer' %}
                  {{ current - mode_2_temp_decrease_step }}
                {% else %}
                  {{ current + mode_2_temp_increase_step }}
                {% endif %}

mode: !input automation_mode
max: !input max_queue
