blueprint:
  name: "IKEA Bilresa Scroll Wheel – Dual Mode Control"
  description: "Control a light using the IKEA Bilresa scroll wheel. Choose between brightness control or color temperature control modes."
  domain: automation
  input:
    control_mode:
      name: "Control Mode"
      description: "Choose whether to control brightness or color temperature"
      default: "brightness"
      selector:
        select:
          options:
            - label: "Brightness Control"
              value: "brightness"
            - label: "Color Temperature Control"
              value: "temperature"

    scroll_right_entity:
      name: "Scroll Right Entity"
      description: "The event entity for scroll right actions"
      selector:
        entity:
          domain: event

    scroll_left_entity:
      name: "Scroll Left Entity"
      description: "The event entity for scroll left actions"
      selector:
        entity:
          domain: event

    button_press_entity:
      name: "Button Press Entity"
      description: "The event entity for button press actions"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "The light to control"
      selector:
        entity:
          domain: light

    # Brightness mode settings
    increase_brightness_step:
      name: "Brightness Increase Step"
      description: "How much to increase brightness per scroll (percentage) - Only for Brightness mode"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    decrease_brightness_step:
      name: "Brightness Decrease Step"
      description: "How much to decrease brightness per scroll (percentage) - Only for Brightness mode"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    brightness_scroll_right_action:
      name: "Brightness: Scroll Right Action"
      description: "What happens when scrolling right in Brightness mode"
      default: "increase"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "increase"
            - label: "Decrease Brightness"
              value: "decrease"

    # Temperature mode settings
    increase_temperature_step:
      name: "Temperature Increase Step"
      description: "How much to increase color temperature per scroll (mireds) - Only for Temperature mode"
      default: 30
      selector:
        number:
          min: 5
          max: 100
          unit_of_measurement: "mireds"

    decrease_temperature_step:
      name: "Temperature Decrease Step"
      description: "How much to decrease color temperature per scroll (mireds) - Only for Temperature mode"
      default: 30
      selector:
        number:
          min: 5
          max: 100
          unit_of_measurement: "mireds"

    temperature_scroll_right_action:
      name: "Temperature: Scroll Right Action"
      description: "What happens when scrolling right in Temperature mode"
      default: "warmer"
      selector:
        select:
          options:
            - label: "Warmer (increase mireds)"
              value: "warmer"
            - label: "Cooler (decrease mireds)"
              value: "cooler"

    automation_mode:
      name: "Automation Mode"
      description: "How to handle multiple triggers"
      default: "queued"
      selector:
        select:
          options:
            - label: "Queued (recommended for smooth scrolling)"
              value: "queued"
            - label: "Single (ignore new triggers while running)"
              value: "single"
            - label: "Restart (restart on new trigger)"
              value: "restart"
            - label: "Parallel (run multiple instances)"
              value: "parallel"

    max_queue:
      name: "Maximum Queue Size"
      description: "Maximum number of queued scroll actions (only applies in queued mode)"
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "actions"

trigger:
  - platform: state
    entity_id: !input scroll_right_entity
    id: scroll_right
  - platform: state
    entity_id: !input scroll_left_entity
    id: scroll_left
  - platform: state
    entity_id: !input button_press_entity
    id: button_press

action:
  - variables:
      target: !input target_light
      mode: !input control_mode
      # Brightness variables
      brightness_increase_step: !input increase_brightness_step
      brightness_decrease_step: !input decrease_brightness_step
      brightness_scroll_direction: !input brightness_scroll_right_action
      # Temperature variables
      temp_increase_step: !input increase_temperature_step
      temp_decrease_step: !input decrease_temperature_step
      temp_scroll_direction: !input temperature_scroll_right_action

  - choose:
      # Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: button_press
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ target }}"

      # Scroll right
      - conditions:
          - condition: trigger
            id: scroll_right
        sequence:
          - choose:
              # Brightness mode
              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      brightness_step_pct: >-
                        {% if brightness_scroll_direction == 'increase' %}
                          {{ brightness_increase_step }}
                        {% else %}
                          {{ -brightness_decrease_step }}
                        {% endif %}
              # Temperature mode
              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'temperature' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      color_temp: >-
                        {% set current = state_attr(target, 'color_temp') | int %}
                        {% if temp_scroll_direction == 'warmer' %}
                          {{ current + temp_increase_step }}
                        {% else %}
                          {{ current - temp_decrease_step }}
                        {% endif %}

      # Scroll left
      - conditions:
          - condition: trigger
            id: scroll_left
        sequence:
          - choose:
              # Brightness mode
              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'brightness' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      brightness_step_pct: >-
                        {% if brightness_scroll_direction == 'increase' %}
                          {{ -brightness_decrease_step }}
                        {% else %}
                          {{ brightness_increase_step }}
                        {% endif %}
              # Temperature mode
              - conditions:
                  - condition: template
                    value_template: "{{ mode == 'temperature' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ target }}"
                    data:
                      color_temp: >-
                        {% set current = state_attr(target, 'color_temp') | int %}
                        {% if temp_scroll_direction == 'warmer' %}
                          {{ current - temp_decrease_step }}
                        {% else %}
                          {{ current + temp_increase_step }}
                        {% endif %}

mode: !input automation_mode
max: !input max_queue
