blueprint:
  name: "IKEA Bilresa Scroll Wheel – 3 Modes Control"
  description: "Control up to 3 different lights or functions using the 3 modes of the IKEA Bilresa scroll wheel. Each mode has scroll right, scroll left, and button press."
  domain: automation

  input:
    scroll_wheel_entity:
      name: "Scroll Wheel Entity"
      description: "The event entity for the scroll wheel"
      selector:
        entity:
          domain: event

    # ════════════════════════════════════════════════════════════
    # MODE 1
    # ════════════════════════════════════════════════════════════
    mode1_enabled:
      name: "Mode 1 – Enable"
      description: "Enable Mode 1 controls"
      default: true
      selector:
        boolean:

    mode1_target_light:
      name: "Mode 1 – Target Light"
      description: "Light to control in Mode 1"
      default: ""
      selector:
        entity:
          domain: light

    mode1_control_type:
      name: "Mode 1 – Control Type"
      description: "What to control with scroll wheel in Mode 1"
      selector:
        select:
          options:
            - label: "Brightness"
              value: "brightness"
            - label: "Color Temperature"
              value: "color_temp"
      default: "brightness"

    mode1_scroll_direction:
      name: "Mode 1 – Scroll Direction"
      description: "Which direction increases brightness/warmth"
      selector:
        select:
          options:
            - label: "Right increases"
              value: "right_up"
            - label: "Left increases"
              value: "left_up"
      default: "right_up"

    mode1_step_size:
      name: "Mode 1 – Step Size"
      description: "Step size for brightness (%) or color temp (mireds)"
      default: 5
      selector:
        number:
          min: 1
          max: 50

    mode1_button_action:
      name: "Mode 1 – Button Press Action"
      description: "What happens when you press the center button"
      selector:
        select:
          options:
            - label: "Toggle light on/off"
              value: "toggle"
            - label: "Turn on"
              value: "turn_on"
            - label: "Turn off"
              value: "turn_off"
            - label: "Set to 25% brightness"
              value: "brightness_25"
            - label: "Set to 50% brightness"
              value: "brightness_50"
            - label: "Set to 75% brightness"
              value: "brightness_75"
            - label: "Set to 100% brightness"
              value: "brightness_100"
      default: "toggle"

    # ════════════════════════════════════════════════════════════
    # MODE 2
    # ════════════════════════════════════════════════════════════
    mode2_enabled:
      name: "Mode 2 – Enable"
      description: "Enable Mode 2 controls"
      default: false
      selector:
        boolean:

    mode2_target_light:
      name: "Mode 2 – Target Light"
      description: "Light to control in Mode 2"
      default: ""
      selector:
        entity:
          domain: light

    mode2_control_type:
      name: "Mode 2 – Control Type"
      description: "What to control with scroll wheel in Mode 2"
      selector:
        select:
          options:
            - label: "Brightness"
              value: "brightness"
            - label: "Color Temperature"
              value: "color_temp"
      default: "brightness"

    mode2_scroll_direction:
      name: "Mode 2 – Scroll Direction"
      description: "Which direction increases brightness/warmth"
      selector:
        select:
          options:
            - label: "Right increases"
              value: "right_up"
            - label: "Left increases"
              value: "left_up"
      default: "right_up"

    mode2_step_size:
      name: "Mode 2 – Step Size"
      description: "Step size for brightness (%) or color temp (mireds)"
      default: 5
      selector:
        number:
          min: 1
          max: 50

    mode2_button_action:
      name: "Mode 2 – Button Press Action"
      description: "What happens when you press the center button"
      selector:
        select:
          options:
            - label: "Toggle light on/off"
              value: "toggle"
            - label: "Turn on"
              value: "turn_on"
            - label: "Turn off"
              value: "turn_off"
            - label: "Set to 25% brightness"
              value: "brightness_25"
            - label: "Set to 50% brightness"
              value: "brightness_50"
            - label: "Set to 75% brightness"
              value: "brightness_75"
            - label: "Set to 100% brightness"
              value: "brightness_100"
      default: "toggle"

    # ════════════════════════════════════════════════════════════
    # MODE 3
    # ════════════════════════════════════════════════════════════
    mode3_enabled:
      name: "Mode 3 – Enable"
      description: "Enable Mode 3 controls"
      default: false
      selector:
        boolean:

    mode3_target_light:
      name: "Mode 3 – Target Light"
      description: "Light to control in Mode 3"
      default: ""
      selector:
        entity:
          domain: light

    mode3_control_type:
      name: "Mode 3 – Control Type"
      description: "What to control with scroll wheel in Mode 3"
      selector:
        select:
          options:
            - label: "Brightness"
              value: "brightness"
            - label: "Color Temperature"
              value: "color_temp"
      default: "color_temp"

    mode3_scroll_direction:
      name: "Mode 3 – Scroll Direction"
      description: "Which direction increases brightness/warmth"
      selector:
        select:
          options:
            - label: "Right increases"
              value: "right_up"
            - label: "Left increases"
              value: "left_up"
      default: "right_up"

    mode3_step_size:
      name: "Mode 3 – Step Size"
      description: "Step size for brightness (%) or color temp (mireds)"
      default: 25
      selector:
        number:
          min: 1
          max: 50

    mode3_button_action:
      name: "Mode 3 – Button Press Action"
      description: "What happens when you press the center button"
      selector:
        select:
          options:
            - label: "Toggle light on/off"
              value: "toggle"
            - label: "Turn on"
              value: "turn_on"
            - label: "Turn off"
              value: "turn_off"
            - label: "Set to 25% brightness"
              value: "brightness_25"
            - label: "Set to 50% brightness"
              value: "brightness_50"
            - label: "Set to 75% brightness"
              value: "brightness_75"
            - label: "Set to 100% brightness"
              value: "brightness_100"
      default: "toggle"

    # ════════════════════════════════════════════════════════════
    # SHARED SETTINGS
    # ════════════════════════════════════════════════════════════
    color_temp_min:
      name: "Color Temperature – Minimum (mireds)"
      description: "Warmest color temperature (lower = warmer/yellow)"
      default: 153
      selector:
        number:
          min: 153
          max: 500

    color_temp_max:
      name: "Color Temperature – Maximum (mireds)"
      description: "Coolest color temperature (higher = cooler/blue)"
      default: 500
      selector:
        number:
          min: 153
          max: 500

trigger:
  - platform: state
    entity_id: !input scroll_wheel_entity

action:
  - variables:
      # Get event details
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"

      # Determine which mode (1, 2, or 3) based on event type
      # Assuming event types like: mode1_rotate_right, mode2_rotate_left, mode3_button_press, etc.
      current_mode: >-
        {% if 'mode_1' in event_type or event_type in ['rotate_right', 'rotate_left', 'short_release'] %}
          1
        {% elif 'mode_2' in event_type %}
          2
        {% elif 'mode_3' in event_type %}
          3
        {% else %}
          1
        {% endif %}

      # Get action type (scroll_right, scroll_left, or button)
      is_scroll_right: "{{ 'rotate_right' in event_type }}"
      is_scroll_left: "{{ 'rotate_left' in event_type }}"
      is_button: "{{ 'press' in event_type or 'release' in event_type }}"

      # Load mode-specific settings
      mode1_on: !input mode1_enabled
      mode1_light: !input mode1_target_light
      mode1_type: !input mode1_control_type
      mode1_dir: !input mode1_scroll_direction
      mode1_step: !input mode1_step_size
      mode1_btn: !input mode1_button_action

      mode2_on: !input mode2_enabled
      mode2_light: !input mode2_target_light
      mode2_type: !input mode2_control_type
      mode2_dir: !input mode2_scroll_direction
      mode2_step: !input mode2_step_size
      mode2_btn: !input mode2_button_action

      mode3_on: !input mode3_enabled
      mode3_light: !input mode3_target_light
      mode3_type: !input mode3_control_type
      mode3_dir: !input mode3_scroll_direction
      mode3_step: !input mode3_step_size
      mode3_btn: !input mode3_button_action

      temp_min: !input color_temp_min
      temp_max: !input color_temp_max

      # Select active mode settings
      active_light: >-
        {% if current_mode == 1 %}
          {{ mode1_light }}
        {% elif current_mode == 2 %}
          {{ mode2_light }}
        {% else %}
          {{ mode3_light }}
        {% endif %}

      active_type: >-
        {% if current_mode == 1 %}
          {{ mode1_type }}
        {% elif current_mode == 2 %}
          {{ mode2_type }}
        {% else %}
          {{ mode3_type }}
        {% endif %}

      active_dir: >-
        {% if current_mode == 1 %}
          {{ mode1_dir }}
        {% elif current_mode == 2 %}
          {{ mode2_dir }}
        {% else %}
          {{ mode3_dir }}
        {% endif %}

      active_step: >-
        {% if current_mode == 1 %}
          {{ mode1_step }}
        {% elif current_mode == 2 %}
          {{ mode2_step }}
        {% else %}
          {{ mode3_step }}
        {% endif %}

      active_button: >-
        {% if current_mode == 1 %}
          {{ mode1_btn }}
        {% elif current_mode == 2 %}
          {{ mode2_btn }}
        {% else %}
          {{ mode3_btn }}
        {% endif %}

      # Calculate direction (1 for increase, -1 for decrease)
      direction: >-
        {% if is_scroll_right %}
          {{ 1 if active_dir == 'right_up' else -1 }}
        {% else %}
          {{ -1 if active_dir == 'right_up' else 1 }}
        {% endif %}

      # Check if mode is enabled and light is configured
      mode_active: >-
        {% if current_mode == 1 %}
          {{ mode1_on and mode1_light != '' }}
        {% elif current_mode == 2 %}
          {{ mode2_on and mode2_light != '' }}
        {% else %}
          {{ mode3_on and mode3_light != '' }}
        {% endif %}

  # Only proceed if mode is enabled and light is configured
  - condition: template
    value_template: "{{ mode_active }}"

  - choose:
      # ═══════════════════════════════════════════════════════════
      # BUTTON PRESS
      # ═══════════════════════════════════════════════════════════
      - conditions:
          - condition: template
            value_template: "{{ is_button }}"
        sequence:
          - choose:
              - conditions: "{{ active_button == 'toggle' }}"
                sequence:
                  - service: light.toggle
                    target:
                      entity_id: "{{ active_light }}"

              - conditions: "{{ active_button == 'turn_on' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"

              - conditions: "{{ active_button == 'turn_off' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ active_light }}"

              - conditions: "{{ active_button == 'brightness_25' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      brightness_pct: 25

              - conditions: "{{ active_button == 'brightness_50' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      brightness_pct: 50

              - conditions: "{{ active_button == 'brightness_75' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      brightness_pct: 75

              - conditions: "{{ active_button == 'brightness_100' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ active_light }}"
                    data:
                      brightness_pct: 100

      # ═══════════════════════════════════════════════════════════
      # SCROLL – BRIGHTNESS MODE
      # ═══════════════════════════════════════════════════════════
      - conditions:
          - condition: template
            value_template: "{{ (is_scroll_right or is_scroll_left) and active_type == 'brightness' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ active_light }}"
            data:
              brightness_step_pct: "{{ active_step | int * direction | int }}"

      # ═══════════════════════════════════════════════════════════
      # SCROLL – COLOR TEMPERATURE MODE
      # ═══════════════════════════════════════════════════════════
      - conditions:
          - condition: template
            value_template: "{{ (is_scroll_right or is_scroll_left) and active_type == 'color_temp' }}"
        sequence:
          - variables:
              # In mireds: lower = warmer, higher = cooler
              # "Increasing warmth" means decreasing mireds, so we invert direction
              current_temp: "{{ state_attr(active_light, 'color_temp') | int(250) }}"
              temp_change: "{{ active_step | int * direction | int * -1 }}"
              new_temp: >-
                {% set new_val = current_temp | int + temp_change | int %}
                {% if new_val < temp_min | int %}
                  {{ temp_min | int }}
                {% elif new_val > temp_max | int %}
                  {{ temp_max | int }}
                {% else %}
                  {{ new_val }}
                {% endif %}

          - service: light.turn_on
            target:
              entity_id: "{{ active_light }}"
            data:
              color_temp: "{{ new_temp | int }}"

mode: queued
max: 20
