blueprint:
  name: "IKEA Bilresa Scroll Wheel – Brightness & Temperature Control"
  description: "Control a light using the IKEA Bilresa scroll wheel. Mode 1 controls brightness, Mode 2 controls color temperature. Use different scroll wheel positions for each mode."
  domain: automation
  input:
    # Mode 1: Brightness Control
    mode_1_scroll_right_entity:
      name: "Brightness: Scroll Right Entity"
      description: "The event entity for scroll right actions (Brightness control)"
      selector:
        entity:
          domain: event

    mode_1_scroll_left_entity:
      name: "Brightness: Scroll Left Entity"
      description: "The event entity for scroll left actions (Brightness control)"
      selector:
        entity:
          domain: event

    mode_1_button_press_entity:
      name: "Brightness: Button Press Entity"
      description: "The event entity for button press actions (Brightness control - toggles light)"
      selector:
        entity:
          domain: event

    mode_1_target_light:
      name: "Brightness: Target Light"
      description: "The light to control for brightness"
      selector:
        entity:
          domain: light

    mode_1_increase_brightness_step:
      name: "Brightness: Increase Step"
      description: "How much to increase brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    mode_1_decrease_brightness_step:
      name: "Brightness: Decrease Step"
      description: "How much to decrease brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    mode_1_scroll_right_action:
      name: "Brightness: Scroll Right Action"
      description: "What happens when scrolling right for brightness"
      default: "increase"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "increase"
            - label: "Decrease Brightness"
              value: "decrease"

    # Mode 2: Temperature Control
    mode_2_scroll_right_entity:
      name: "Temperature: Scroll Right Entity"
      description: "The event entity for scroll right actions (Temperature control)"
      selector:
        entity:
          domain: event

    mode_2_scroll_left_entity:
      name: "Temperature: Scroll Left Entity"
      description: "The event entity for scroll left actions (Temperature control)"
      selector:
        entity:
          domain: event

    mode_2_button_press_entity:
      name: "Temperature: Button Press Entity"
      description: "The event entity for button press actions (Temperature control - toggles light)"
      selector:
        entity:
          domain: event

    mode_2_target_light:
      name: "Temperature: Target Light"
      description: "The light to control for color temperature (must support color temperature)"
      selector:
        entity:
          domain: light

    mode_2_increase_temperature_step:
      name: "Temperature: Increase Step (Cooler)"
      description: "How much to increase color temperature per scroll (Kelvin) - makes light cooler/bluer"
      default: 300
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: "K"

    mode_2_decrease_temperature_step:
      name: "Temperature: Decrease Step (Warmer)"
      description: "How much to decrease color temperature per scroll (Kelvin) - makes light warmer/yellower"
      default: 300
      selector:
        number:
          min: 50
          max: 1000
          unit_of_measurement: "K"

    mode_2_scroll_right_action:
      name: "Temperature: Scroll Right Action"
      description: "What happens when scrolling right for temperature"
      default: "warmer"
      selector:
        select:
          options:
            - label: "Warmer (decrease Kelvin)"
              value: "warmer"
            - label: "Cooler (increase Kelvin)"
              value: "cooler"

    mode_2_min_kelvin:
      name: "Temperature: Minimum Kelvin"
      description: "Minimum color temperature (warmest)"
      default: 2000
      selector:
        number:
          min: 1500
          max: 4000
          unit_of_measurement: "K"

    mode_2_max_kelvin:
      name: "Temperature: Maximum Kelvin"
      description: "Maximum color temperature (coolest)"
      default: 6500
      selector:
        number:
          min: 4000
          max: 10000
          unit_of_measurement: "K"

    # Smoothing settings
    transition_time:
      name: "Transition Time"
      description: "How long the light takes to transition between values (seconds). Lower = more responsive, higher = smoother."
      default: 0.2
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
          unit_of_measurement: "s"

    # Common settings
    automation_mode:
      name: "Automation Mode"
      description: "How to handle multiple triggers"
      default: "restart"
      selector:
        select:
          options:
            - label: "Restart (recommended - interrupts previous action for instant response)"
              value: "restart"
            - label: "Queued (queue all scroll actions - can feel laggy)"
              value: "queued"
            - label: "Single (ignore new triggers while running)"
              value: "single"
            - label: "Parallel (run multiple instances simultaneously)"
              value: "parallel"

    max_queue:
      name: "Maximum Queue Size"
      description: "Maximum number of queued scroll actions (only applies in queued mode)"
      default: 20
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "actions"

trigger:
  # Brightness triggers (Mode 1)
  - platform: state
    entity_id: !input mode_1_scroll_right_entity
    id: brightness_scroll_right
  - platform: state
    entity_id: !input mode_1_scroll_left_entity
    id: brightness_scroll_left
  - platform: state
    entity_id: !input mode_1_button_press_entity
    id: brightness_button_press
  # Temperature triggers (Mode 2)
  - platform: state
    entity_id: !input mode_2_scroll_right_entity
    id: temperature_scroll_right
  - platform: state
    entity_id: !input mode_2_scroll_left_entity
    id: temperature_scroll_left
  - platform: state
    entity_id: !input mode_2_button_press_entity
    id: temperature_button_press

action:
  - variables:
      # Brightness variables
      brightness_target: !input mode_1_target_light
      brightness_increase_step: !input mode_1_increase_brightness_step
      brightness_decrease_step: !input mode_1_decrease_brightness_step
      brightness_scroll_direction: !input mode_1_scroll_right_action
      # Temperature variables
      temperature_target: !input mode_2_target_light
      temp_increase_step: !input mode_2_increase_temperature_step
      temp_decrease_step: !input mode_2_decrease_temperature_step
      temp_scroll_direction: !input mode_2_scroll_right_action
      temp_min: !input mode_2_min_kelvin
      temp_max: !input mode_2_max_kelvin
      # Smoothing
      transition: !input transition_time

  - choose:
      # Brightness: Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: brightness_button_press
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ brightness_target }}"

      # Brightness: Scroll right
      - conditions:
          - condition: trigger
            id: brightness_scroll_right
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ brightness_target }}"
            data:
              transition: "{{ transition }}"
              brightness_step_pct: >-
                {% if brightness_scroll_direction == 'increase' %}
                  {{ brightness_increase_step }}
                {% else %}
                  {{ -brightness_decrease_step }}
                {% endif %}

      # Brightness: Scroll left
      - conditions:
          - condition: trigger
            id: brightness_scroll_left
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ brightness_target }}"
            data:
              transition: "{{ transition }}"
              brightness_step_pct: >-
                {% if brightness_scroll_direction == 'increase' %}
                  {{ -brightness_decrease_step }}
                {% else %}
                  {{ brightness_increase_step }}
                {% endif %}

      # Temperature: Button press - Toggle on/off
      - conditions:
          - condition: trigger
            id: temperature_button_press
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ temperature_target }}"

      # Temperature: Scroll right
      - conditions:
          - condition: trigger
            id: temperature_scroll_right
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ temperature_target }}"
            data:
              transition: "{{ transition }}"
              color_temp_kelvin: >-
                {% set current = state_attr(temperature_target, 'color_temp_kelvin') %}
                {% if current is none %}
                  {% set current = 4000 %}
                {% endif %}
                {% set current = current | int(4000) %}
                {% if temp_scroll_direction == 'warmer' %}
                  {{ [current - temp_decrease_step, temp_min] | max }}
                {% else %}
                  {{ [current + temp_increase_step, temp_max] | min }}
                {% endif %}

      # Temperature: Scroll left
      - conditions:
          - condition: trigger
            id: temperature_scroll_left
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ temperature_target }}"
            data:
              transition: "{{ transition }}"
              color_temp_kelvin: >-
                {% set current = state_attr(temperature_target, 'color_temp_kelvin') %}
                {% if current is none %}
                  {% set current = 4000 %}
                {% endif %}
                {% set current = current | int(4000) %}
                {% if temp_scroll_direction == 'warmer' %}
                  {{ [current + temp_increase_step, temp_max] | min }}
                {% else %}
                  {{ [current - temp_decrease_step, temp_min] | max }}
                {% endif %}

mode: !input automation_mode
max: !input max_queue
