blueprint:
  name: "IKEA Bilresa Scroll Wheel – Simple Brightness Control"
  description: "Control a light's brightness using the IKEA Bilresa scroll wheel. Scroll to adjust brightness, press to toggle on/off."
  domain: automation

  input:
    scroll_wheel_entity:
      name: "Scroll Wheel Entity"
      description: "The event entity for the scroll wheel"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "The light to control"
      selector:
        entity:
          domain: light

    increase_brightness_step:
      name: "Brightness Increase Step"
      description: "How much to increase brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    decrease_brightness_step:
      name: "Brightness Decrease Step"
      description: "How much to decrease brightness per scroll (percentage)"
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    scroll_right_action:
      name: "Scroll Right Action"
      description: "What happens when scrolling right"
      default: "increase"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "increase"
            - label: "Decrease Brightness"
              value: "decrease"

trigger:
  - platform: state
    entity_id: !input scroll_wheel_entity

action:
  - variables:
      event_type: "{{ state_attr(trigger.entity_id, 'event_type') }}"
      is_scroll_right: "{{ 'rotate_right' in event_type }}"
      is_scroll_left: "{{ 'rotate_left' in event_type }}"
      is_button: "{{ 'press' in event_type or 'release' in event_type }}"
      target: !input target_light
      increase_step: !input increase_brightness_step
      decrease_step: !input decrease_brightness_step
      scroll_right_direction: !input scroll_right_action

  - choose:
      # Button press - Toggle on/off
      - conditions:
          - condition: template
            value_template: "{{ is_button }}"
        sequence:
          - service: light.toggle
            target:
              entity_id: "{{ target }}"

      # Scroll right
      - conditions:
          - condition: template
            value_template: "{{ is_scroll_right }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target }}"
            data:
              brightness_step_pct: >-
                {% if scroll_right_direction == 'increase' %}
                  {{ increase_step }}
                {% else %}
                  {{ -decrease_step }}
                {% endif %}

      # Scroll left
      - conditions:
          - condition: template
            value_template: "{{ is_scroll_left }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ target }}"
            data:
              brightness_step_pct: >-
                {% if scroll_right_direction == 'increase' %}
                  {{ -decrease_step }}
                {% else %}
                  {{ increase_step }}
                {% endif %}

mode: queued
max: 20